options:
  ipmi-exporter-version:
    type: string
    default: "1.8.0"
    description: >
      The ipmi-exporter version to install.
  listen-address:
    type: string
    default: "0.0.0.0:9290"
    description: The address to listen to.