{
 "title": "IPMI Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(ipmi_bmc_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Production Server Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Power Consumption in Watts",
   "type": "gauge",
   "description": "A summary of total watt consumption used by scraped servers",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipmi_dcmi_power_consumption_watts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption in watts",
   "type": "timeseries",
   "description": "Graph of all servers total power consumption in watt",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 1 },
   "targets": [
    { "expr": "ipmi_bmc_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{name=~\"CPU Temp|CPU0_TEMP\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "General System Info ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_chassis_power_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "ipmi_bmc_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan speed in rotations per minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "ipmi_temperature_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reported state of a voltage sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage reading in Volts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}